<?php

namespace BlogBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSortedByDate()
    {
        return $this->createQueryBuilder( 'a' )
            ->select( 'a' )
            ->orderBy( 'a.createdAt', 'DESC' )
            ->where( 'a.id != 2' )
            ->getQuery()
            ->getResult();
    }
}
