<?php

namespace BlogBundle\Repository;

/**
 * TeacherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherRepository extends \Doctrine\ORM\EntityRepository
{   
    public function findTeachers()
    {
        return $this->createQueryBuilder( 'a' )
            ->select( 'a' )
            ->getQuery()
            ->getResult();
    }
}
